Add initial support for Google Play Games

diff --git a/tools/build-system/scripts/build-android b/tools/build-system/scripts/build-android
--- a/tools/build-system/scripts/build-android
+++ b/tools/build-system/scripts/build-android
@@ -32,11 +32,15 @@ if [ -n "$PROJECT_DIRECTORY" ]; then
 		SUFFIX=/
 		LIB_NAME=${d#$PREFIX}
 		LIB_NAME=${LIB_NAME%$SUFFIX}
-		ANDROID_ABI_RESULTS="$ANDROID_ABI_RESULTS $LIB_NAME"
 
-		if ! [ -e "$d/libmain.so" ]; then
-			echo "build-android failed for $PROJECT_DIRECTORY: missing library '$d/libmain.so'" | tee -a "$PROJECT_DIRECTORY/log-Release-Android"
-			exit
+		# Ignore any non-ABI files
+		if [ "$LIB_NAME" != "support-annotations.jar" ]; then
+			ANDROID_ABI_RESULTS="$ANDROID_ABI_RESULTS $LIB_NAME"
+
+			if ! [ -e "$d/libmain.so" ]; then
+				echo "build-android failed for $PROJECT_DIRECTORY: missing library '$d/libmain.so'" | tee -a "$PROJECT_DIRECTORY/log-Release-Android"
+				exit
+			fi
 		fi
 	done
 
