Make Android (re)build fail if any ABI target fails
Before this change, if an ABI target failed when compiling its first
library, the script would not realize that an ABI target had failed.

The script was merely checking for ABI targets based on their respective
directories in android/libs

Now, it also checks the build-system-targets file to determine ALL
targeted ABIs, and ensure that none are missed.

diff --git a/tools/build-system/scripts/rebuild-android b/tools/build-system/scripts/rebuild-android
--- a/tools/build-system/scripts/rebuild-android
+++ b/tools/build-system/scripts/rebuild-android
@@ -14,39 +14,59 @@ if [ -n "$PROJECT_DIRECTORY" ]; then
 
 	android/linux/rebuild $PROJECT_DIRECTORY >> "$PROJECT_DIRECTORY/log-Release-Android"
 
-	ALL_LIBS_EXIST="true"
+	ANDROID_ABI_TARGETS=""
+
+	while read line
+	do
+		if [[ $line == Android* ]]; then
+			ANDROID_ABI_TARGETS=$(echo $line | sed s/Android//)
+		fi
+	done <"$PROJECT_DIRECTORY/development/build-system-targets"
+
+	ANDROID_ABI_RESULTS=""
+
 	for d in $PROJECT_DIRECTORY/development/android/libs/* ; do
+		PREFIX=$PROJECT_DIRECTORY/development/android/libs/
+		SUFFIX=/
+		LIB_NAME=${d#$PREFIX}
+		LIB_NAME=${LIB_NAME%$SUFFIX}
+		ANDROID_ABI_RESULTS="$ANDROID_ABI_RESULTS $LIB_NAME"
+
 		if ! [ -e "$d/libRakNet.so" ]; then
-			ALL_LIBS_EXIST="false"
-			break
+			echo "rebuild-android failed for $PROJECT_DIRECTORY: missing library '$d/libRakNet.so'"
+			exit
 		fi
 
 		if ! [ -e "$d/libSDL2.so" ]; then
-			ALL_LIBS_EXIST="false"
-			break
+			echo "rebuild-android failed for $PROJECT_DIRECTORY: missing library '$d/libSDL2.so'"
+			exit
 		fi
 
 		if ! [ -e "$d/libSDL2_image.so" ]; then
-			ALL_LIBS_EXIST="false"
-			break
+			echo "rebuild-android failed for $PROJECT_DIRECTORY: missing library '$d/libSDL2_image.so'"
+			exit
 		fi
 
 		if ! [ -e "$d/libSDL2_mixer.so" ]; then
-			ALL_LIBS_EXIST="false"
-			break
+			echo "rebuild-android failed for $PROJECT_DIRECTORY: missing library '$d/libSDL2_mixer.so'"
+			exit
 		fi
 
 		if ! [ -e "$d/libmain.so" ]; then
-			ALL_LIBS_EXIST="false"
-			break
+			echo "rebuild-android failed for $PROJECT_DIRECTORY: missing library '$d/libmain.so'"
+			exit
 		fi
 	done
 
-	if [ "$ALL_LIBS_EXIST" == "true" ]; then
-		android/linux/ant $PROJECT_DIRECTORY release rebuild >> "$PROJECT_DIRECTORY/log-Release-Android"
-	else
-		echo "build-android failed for $PROJECT_DIRECTORY"
-	fi
+	IFS=' ' read -a ARRAY <<< "$ANDROID_ABI_TARGETS"
+	for i in "${ARRAY[@]}" ; do
+		if ! [[ $ANDROID_ABI_RESULTS == *"$i"* ]]; then
+			echo "rebuild-android failed for $PROJECT_DIRECTORY: missing ABI '$i'"
+			exit
+		fi
+	done
+
+	android/linux/ant $PROJECT_DIRECTORY release rebuild >> "$PROJECT_DIRECTORY/log-Release-Android"
 else
 	echo "rebuild-android - rebuild the android target for the passed project"
 	echo "Usage: rebuild-android PROJECT_DIRECTORY"
